#Installing nginx
- name: nginx installation and start the service
  hosts: web
  become: yes #getting the root access
  tasks:
  - name: nginx installation
    ansible.builtin.package: #module to install the package
      name: nginx
      state: present
  - name: starting and enabling the service 
    ansible.builtin.service: #module to start the service
      name: nginx
      state: started
      enabled: yes
  
#Installing MySQL
- name: mysql-server installation and start the service
  hosts: web
  become: yes
  tasks: 
  - name: mysql-server installation
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: starting and enabling the service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes