- name: Variables
  hosts: web
  vars: #Declaring vars in Play level
    peru: "Swapna"
    age: "27"
    education: "Post Graduation"
  tasks:
  - name: Information 1 Normal way
    ansible.builtin.debug:
      msg: "Hi I'm Ganesh, 24 years old completed my Graduation"

  - name: Information 2 Vars through Play level 
    ansible.builtin.debug:
      msg: "Hi I'm {{peru}}, {{age}} years old completed my {{education}}"

  - name: Information 3 Vars through task level 
    vars: #Declaring vars in task level
      peru: "Narendra"
      age: "51"
      education: "10th"
    ansible.builtin.debug:
      msg: "Hi I'm {{peru}}, {{age}} years old completed my {{education}}"

  
