- name: Variables
  hosts: web
  vars:
    peru: "Swapna"
    age: "27"
    education: Post Graduation
  tasks:
  - name: Informaton 1
    ansible.builtin.debug:
      msg: "Hi I'm Ganesh, 24 years old completed my Graduation"

  - name: Information 2
    ansible.builtin.debug:
      msg: "Hi I'm {{peru}}, {{age}} years old completed my {{education}}"