- name: Variables
  hosts: web
  vars_prompt:
  - name: peru
    prompt: Please enter the name
  - name: age
    prompt: Please enter the age
  - name: education
    prompt: Please enter the education details
  tasks: 
    - name: Information 5 Vars through prompt
      ansible.builtin.debug:
        msg: "Hi I'm {{peru}}, {{age}} years old completed my {{education}}"