- name: Datatypes
  hosts: localhost
  #connection: local #when connecting to local host
  vars:
    peru: "Ganesh" #string
    age: 24 #int
    hobbies: #list
      - playing
      - watching movies
      - walking
      - running
    male: true #boolean
    education: #map/dictionary
      tenth: Sri Chaithanya
      inter: Narayana # again this is string
      btech: Saveetha
      branch: # again this is list
       - ECE
  tasks:
    - name: My details
      ansible.builtin.debug:
        msg: "My name is {{peru}}, {{age}} years old completed my 10th at {{education.tenth}}, studies intermediat at {{education.inter}}, went to {{education.btech}} and joined {{education.branch[0]}}"
    - name: To call list & dictionary
      ansible.builtin.debug:
        msg: "My {{hobbies}} and My {{education}}"