- name: To check given number is greater or lesser
  hosts: localhost
  vars_prompt:
    - name : number
      prompt: Please enter a number
      private: false #By default prompt is confidential it won't show content we entered
  tasks:
    - name: Print this if number is greater than or equal to 10
      ansible.builtin.debug:
        msg: "Given number is greater than or equal to 10"
      when: number >= 10 #Expression

    - name: Print this if number is less than 10
      ansible.builtin.debug:
        msg: "Given number is less than 10"
      when: number < 10 #Expression
