- name: Gathering facts
  hosts: web
  become: yes
  tasks:
    - name: Prints the facts
      ansible.builtin.debug:
        msg: "{{ansible_facts}}"

    - name: Install nginx for RedHat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install nginx for Ubuntu
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Ubuntu"

    #Or we can use module package
    - name: Install nginx using module package
      ansible.builtin.package:
        name: nginx
        state: present
      
