- name: Loops Practice
  hosts: web
  tasks:
    - name: Printing names
      ansible.builtin.debug:
        msg: "Hello {{item}}}"
      gana:
        - Ganesh
        - Bhanu
        - Swapna
        - Amrutha
        - Narendra
        - Vibha