- name: Installing packages using Loops
  hosts: web
  become: yes
  tasks:
    - name: Installing packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - mysql
        - nginx
        - git
        - httpd
    
    #Loops in advance way
    - name: Loops in another way
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - {name: mysql, state: present, enabled: yes}
        - {name: nginx, state: absent}
        - {name: git, state: present, enabled: yes}
        - {name: httpd, state: absent}
        - {name: nginx, state: present, enabled: yes}
       
        
