- name: Functions or Filters
  hosts: local
  connection: local
  tasks:
    - name: Printing the default Variable
      ansible.builtin.debug:
        msg: "Hello {{peru | default('Ganesh')}}" #Here "default" is function
        #msg: "Hello {{age | default(24)}}" #If its a number 
    
    - name: Convert to Uppercase
      vars:
        education: "Graduation"
      ansible.builtin.debug:
        msg: "I completed my {{education | upper}}" #Here "upper" is function