- name: Functions or Filters
  hosts: local
  connection: local
  tasks:
    - name: Printing the default Variable
      ansible.builtin.debug:
        msg: "Hello {{peru | default('Ganesh')}}" #Here "default" is a function
        #msg: "Hello {{age | default(24)}}" #If its a number 
    
    - name: Convert to Uppercase
      vars:
        education: "Graduation"
      ansible.builtin.debug:
        msg: "I completed my {{education | upper}}" #Here "upper" is a function

    - name: Convert to Lowercase
      vars:
        native: "Naidupeta"
      ansible.builtin.debug:
        msg: "I'm from {{native | lower}}" #Here "lower" is a function

    - name: Get the Unique numbers
      vars:
        numbers: [1,2,5,7,89,45,3,45,3,2,6]
      ansible.builtin.debug:
        msg: "Unique numbers are {{numbers | unique}}" #Here "unique" is a function

    - name: Get the min and max numbers
      vars: 
        numbers: [1,2,5,7,89,45,3,45,3,2,6]
      ansible.builtin.debug:
        msg: "Min: {{numbers | min}} Max: {{numbers | max}}" #Here min and max are a functions

    - name: Convert dictionary to list
      vars:
        details:
          peru: "Ganesh"
          age: 24
          education: "Graduate"
      ansible.builtin.debug:
          msg: "{{details | dict2items}}" #Here dict2items is a function

    - name: Convert list to dictionary
      vars:
        details:
        - {"key":"peru", "value":"Ganesh"}
        - {"key":age, "value":24}
        - {"key":"education", "value":"Graduate"}
      ansible.builtin.debug:
          msg: "{{details | items2dict}}" #Here items2dict is a function

    - name: Check for valid ip address
      vars:
        my_ip: 129.2.8.900
      ansible.builtin.debug:
        msg: "{{my_ip | ansible.utils.ipv4}}" #Here ansible.utils.ipv4 is a function