- name: Command vs Shell #Command is secure than Shell, prefer to use command if works
  hosts: local
  connection: local
  tasks:
    - name: Execute the command
      ansible.builtin.command: ls -l > /tmp/output.txt #Command won't execute because, command excutes only simple commands
      register: output
      ignore_errors: true
    - name: output
      ansible.builtin.debug:
        msg: "Above result: {{output}}"

    - name: Execute the shell
      ansible.builtin.shell: ls -l > /tmp/output.txt #Shell execute because, shell login to the server and excute commands inside
      register: output
    - name: output
      ansible.builtin.debug:
        msg: "Above result: {{output}}"
